### ISSUE TITLE
Possible to open inbox link instead of participating?

### ISSUE THREAD

**Issue by mrchief** [sindresorhus/notifier-for-github#222] opened 2020-07-13 19:10 UTC
This https://github.com/notifications?query=is%3Aunread provides a cleaner and smaller list to look at and so I was wondering if it's possible to configure this as an option.

![image](https://user-images.githubusercontent.com/781818/87343411-d1543600-c51a-11ea-8dd8-3969c5b83c55.png)

vs

![image](https://user-images.githubusercontent.com/781818/87343458-e29d4280-c51a-11ea-99bf-676a780dc187.png)

**Comment by notlmn** [comment] 2020-07-14 05:09
We redirect you to `/notifications` endpoint based on the server URL the user has provided. From there it is the job of GitHub to add respective filters (based on the last filter you have applied, "All" or "Unread").

-----

If you are being redirected to `/notifications?query=reason:participating`, then that is controlled by this option:

![image](https://user-images.githubusercontent.com/37769974/87386499-357c0600-c5be-11ea-8aab-1ea1d733d9e9.png)

**Comment by mrchief** [comment] 2020-07-14 14:29
Oh I see. While I want unread count for participating, I don't necessarily want my notifications to open on that query. It's why I feel like an option would help here - GH URL is good but you lose control of it - which can be both good and bad.

**Comment by notlmn** [comment] 2020-07-30 16:31
IMO showing notification count for one thing and having a redirect for another thing might confuse the user.

And there's also the issue of handling changes to other filters on changing this field, do we change the filter or keep it the same (eg: when changing participating filter).

**Comment by mrchief** [comment] 2020-07-30 21:40
> IMO showing notification count for one thing and having a redirect for another thing would might confuse the user.

Are you sure? In my experiments, the notification count doesn't change in both the cases. 

You're going to the inbox and that's the same page (as the current url). User can drill down if needed.

**Comment by notlmn** [comment] 2020-07-31 03:21
> In my experiments, the notification count doesn't change in both the cases.

In that case you might want to have participating option unchecked, this would redirect you to the default page with your default filters applied.

**Comment by mrchief** [comment] 2020-07-31 14:27
> In that case you might want to have participating option unchecked, this would redirect you to the default page with your default filters applied.

That produces too many notifications.

**Comment by notlmn** [comment] 2020-08-01 07:38
I'm not sure I understand what you are trying to say.

If you are talking about having different count for notifications, and having to open ad different page as a feature, we need more users for us to put effort into working on it.

Closing this for now.

**Closed as completed by notlmn** 2020-08-01 07:38 UTC

**Comment by mrchief** [comment] 2020-08-02 01:30
> If you are talking about having different count for notifications, and having to open ad different page as a feature, we need more users for us to put effort into working on it.

No. 

All the concerns you raised in previous threads are not going to cause any issues - that's all I'm saying. 

The change I proposed only affects which of these tabs is selected when the page renders
![image](https://user-images.githubusercontent.com/781818/89113370-29a59600-d43e-11ea-9212-ac5415fb9936.png)

There is no other change in Github's behavior.

And if you mean that in order for you to put this behind an option needs more contributors, that's fair.

**Comment by MrMazzone** [comment] 2020-08-02 03:26
@mrchief  Does that not already work for you?  When I select "Unread" it adds the `is:unread` filter which causes the notifications page to load showing only unread notifications.  That's what @notlmn was saying, you can apply whatever filters you want and when you click on the extension it will load the notifications page with those filters.

**Comment by mrchief** [comment] 2020-08-02 03:30
@MrMazzone It doesn't stick. When you click on extension, it takes you to explicitly whatever your filter is, which is one of these:

![image](https://user-images.githubusercontent.com/781818/89114834-b7897d00-d44e-11ea-87be-c14c30267b6b.png)

So even if I click on `Unread`, close my page, click on the extension upon new notifications, I'm taken back to the notifications page with "All" selected.

I think `Unread` doesn't count as a filter per se.

**Comment by mrchief** [comment] 2020-08-02 03:40
Did some more experiments. When I click on this:

![image](https://user-images.githubusercontent.com/781818/89114968-39c67100-d450-11ea-9ef0-2475659d5bf6.png)

I get redirected to https://github.com/notifications which then redirects me to https://github.com/notifications?query=is%3Aunread

When I click on the extension, I get redirected to https://github.com/notifications/participating which then redirects me to https://github.com/notifications?query=reason%3Aparticipating

**Comment by notlmn** [comment] 2020-08-02 07:30
> When I click on the extension, I get redirected to [github.com/notifications/participating](https://github.com/notifications/participating) which then redirects me to [github.com/notifications?query=reason%3Aparticipating](https://github.com/notifications?query=reason%3Aparticipating)

Yes, that's the intended behavior, because you have "participating" option set, as mentioned in https://github.com/sindresorhus/notifier-for-github/issues/222#issuecomment-657969658.

Again, regarding your original question, it doesn't make sense for us to redirect the user to `/notifications` (or any other filter page) when they have "participation" filter set. When you actually have this option set, we redirect you to that specific filter page (which we know for sure exists), because that's what the user meant to do.

Also FYI, GitHub *only* allows "participation" filter in their API as of this writing, any of the new filters you see in UI are not yet available through their API.

I hope this clears all of your questions.

**Comment by mrchief** [comment] 2020-08-02 17:50
@notlmn We're going in circles. All I'm asking is to add an option to make it behave like Github's own bell icon.

**Comment by notlmn** [comment] 2020-08-04 15:18
> All I'm asking is to add an option to make it behave like Github's own bell icon.

It already does.

-------

You're free to open a PR with the changes you are actually thinking of.
