### ISSUE TITLE
Support for new token format

### ISSUE THREAD

**Issue by Eiji7** [sindresorhus/notifier-for-github#247] opened 2021-04-05 23:25 UTC
For more information please see: [Authentication token format updates](https://github.blog/changelog/2021-03-04-authentication-token-format-updates/)

**Comment by sue445** [comment] 2021-04-05 23:48
I think this is resolved at #246, but not be released yet.
Please release new version 🙏

**Comment by Levi-Lesches** [comment] 2021-04-06 00:01
Also, once you regenerate a token, the old one is invalid, and any new tokens use the new format. So I'm stuck with an error!

**Comment by bjeanes** [comment] 2021-04-06 01:30
> Also, once you regenerate a token, the old one is invalid, and any new tokens use the new format. So I'm stuck with an error!

Exactly! I've now locked myself out of being able to use this as I cannot generate an old token format and I did not realise that the Notifier settings validated the format of the token :(

**Comment by sindresorhus** [comment] 2021-04-06 08:47
Duplicate of #244

**Comment by sindresorhus** [comment] 2021-04-06 08:52
The update is out now for Chrome: https://chrome.google.com/webstore/detail/notifier-for-github/lmjdlojahmbbcodnpecnjnmlddbkjhnn

(It will probably take a couple of hours to propagate)

**Closed as completed** 2021-04-06 18:14 UTC
