### ISSUE TITLE
Clicking the icon no longer opens notifications page

### ISSUE THREAD

**Issue by AudriusButkevicius** [sindresorhus/notifier-for-github#211] opened 2020-05-14 20:04 UTC
Seems the latest update broke it 
Version 20.5.14.814

**Comment by AudriusButkevicius** [comment] 2020-05-14 20:09
Seems I had to reinstall the extension

**Comment by AudriusButkevicius** [comment] 2020-05-14 20:15
Nah, there is definitely something wrong with it, it's broken again.

**Comment by AudriusButkevicius** [comment] 2020-05-14 20:36
The packed extension in chrome seems to hang on this line:
```
    async getAll() {
      await this._migrations; // <----
      return this._getAll();
    }
```

**Comment by 0xIslamTaha** [comment] 2020-05-14 21:24
I can confirm the same bug

**Comment by AudriusButkevicius** [comment] 2020-05-14 21:44
The code has not changed for ages, why has there even been a release?

**Comment by jef** [comment] 2020-05-14 22:24
GitHub recently updated their API. Shouldn't have had breaking changes though. Could be something to do with that. Haven't done any research aside from seeing they added quite a bit of API endpoints.

Edit: that being said, I believe notifications is out of beta too.

**Comment by AudriusButkevicius** [comment] 2020-05-14 22:25
It seems CI for the version I described in the original post has failed with messages saying the developer account needs a privacy notice whatever, yet the build still got released, I wonder if its related.

**Comment by jef** [comment] 2020-05-14 22:26
This might be related: https://github.com/sindresorhus/notifier-for-github/commit/9f4c947dd837378a9c4846d5222b3af8c28e0e33

**Comment by AudriusButkevicius** [comment] 2020-05-14 22:29
I don't think it is, that's like 27th of March. It would open an incorrect page, now it doesn't open anything.

**Comment by jef** [comment] 2020-05-14 22:31
Just hit the `https://api.github.com/notifications` API. Still seems to work. Not sure how to really test an extension. I'll try and do some debugging.

**Comment by AudriusButkevicius** [comment] 2020-05-14 22:46
I am fairly positive the issue visible in CI is the cause, someone with access to the developer console needs to address this.

**Comment by 0xIslamTaha** [comment] 2020-05-14 22:53
@AudriusButkevicius is this repo still active?

**Comment by AudriusButkevicius** [comment] 2020-05-14 22:54
I have no idea, I am not a maintainer, just a user.

**Comment by 0xIslamTaha** [comment] 2020-05-14 22:56
@sindresorhus could u kindly check this bug?

**Comment by AudriusButkevicius** [comment] 2020-05-14 23:01
He's the owner of this repo, he gets notifications anyway, I doubt pinging him explicitly makes any difference.

**Comment by BHydden** [comment] 2020-05-14 23:29
FWIW I woke up today to the same issue when it was working properly yesterday, also, not sure if it's relevant, but the extension is stuck on displaying the `1 notification` alert, regardless of how many I actually have.

**Comment by notlmn** [comment] 2020-05-15 07:39
Working on it, trying to find why this extension broke because of `webext-options-sync` and why other extensions didn't.

This is probably because of https://github.com/fregante/webext-options-sync/commit/cd67956942b6008ed15347b2c25d1851d8f1b155, but can't exactly prove it.

@fregante could provide some insights here.

**Comment by AudriusButkevicius** [comment] 2020-05-15 07:57
Ca  we rollback/pin an older dependency and release a new version? 

I see very little point updating dependencies if the extension code is stable and hasn't seen commits for a while. It only adds breakage risk.

**Comment by fregante** [comment] 2020-05-15 09:00
You should be able to safely roll back `webext-options-sync`
1.2.0 shouldn’t be affected. 
1.2.1 is affected

It’s due to https://github.com/fregante/webext-options-sync/blob/359011ada19521392f2b8a12ad9ccdcbd15a55cc/index.ts#L218

It was supposed to make migrations run **only on first launch or update**, but this also blocks the whole `this._migration` promise. 

This is breaking any extensions that await the options in the background page, which explains why most extensions aren’t affected. 

Thanks @AudriusButkevicius for pointing me to the right direction

**Comment by notlmn** [comment] 2020-05-15 09:32
> I see very little point updating dependencies if the extension code is stable and hasn't seen commits for a while. It only adds breakage risk.

Was using `1.2.0` of `webext-options-sync` before, npm on Travis installed most recent one (because of `^`), `1.2.3`, which is also affected.

---------

> Ca we rollback/pin an older dependency and release a new version?

Rolling back requires pinning version in `package.json` or adding `package-lock.json`, instead I [removed migrations](https://github.com/sindresorhus/notifier-for-github/commit/a050aa60701c5ee730ea5b23916a87808e3a0ffa) (temporarily) and released a new version `20.5.15.75`.

Firefox version is already released on AMO and is working fine, but Chrome version might take a little while to pass through their review process.

Will close this issue when Chrome version is published on store, and no issues are found.

Thanks everyone for staying patient for the last 12 hours.

**Comment by notlmn** [comment] 2020-05-15 09:49
Meanwhile to answer some questions

----------

> The code has not changed for ages, why has there even been a release?

There wasn't a release since the code has last changed. Was waiting to fix deployment to stores with https://github.com/notlmn/browser-extension-template/issues/25 and https://github.com/notlmn/browser-extension-template/issues/28, before making a new release. But I eventually forgot about them with the active day job (internship) I have.

------------

> It seems CI for the version I described in the original post has failed with messages saying the developer account needs a privacy notice whatever, yet the build still got released, I wonder if its related.''

This is what stopped me from testing the version released to Chrome store, because it wasn't published to the store yet.

------------

> is this repo still active?

Yup it is 😅

**Comment by notlmn** [comment] 2020-05-15 10:03
Version `20.5.15.751` should now be available on both Chrome and Firefox stores.

Don't mind the recent build failure, that will be fixed over this weekend.

Feel free to open new issues if anything else comes up.

**Closed as completed by notlmn** 2020-05-15 10:03 UTC
Labels: bug
