### ISSUE TITLE
Shorter Intervals

### ISSUE THREAD

**Issue by vinkla** [sindresorhus/notifier-for-github#17] opened 2015-04-16 06:35 UTC
The chrome extension works great and I use it every day. Though, there is one thing I would like to update. The notification fetching interval. Sometime it can take quite a long to update the little notification badge on the icon. Maybe we could add it to the settings page? Then everyone could specify their own preferences. What do you think?

**Comment by sindresorhus** [comment] 2015-04-16 07:12
Duplicate of #11

**Comment by vinkla** [comment] 2015-04-16 07:13
Okay. Thanks.

**Closed as completed by sindresorhus** 2015-04-16 07:12 UTC
