### ISSUE TITLE
Stopped working on network changes or after connecting to VPN

### ISSUE THREAD

**Issue by kutsan** [sindresorhus/notifier-for-github#138] opened 2017-12-09 20:27 UTC
The extension icon turns to "off" state continuously after successfully connecting to a VPN server.

**Comment by notlmn** [comment] 2018-06-29 16:39
Can you clarify on "continuously". Does the extension stay in "off" state forever?

**Comment by notlmn** [comment] 2018-06-29 17:32
Duplicate of #132.

**Closed by notlmn** 2018-06-29 17:32 UTC
