### ISSUE TITLE
Does only show them when clicked once

### ISSUE THREAD

**Issue by thebigsmileXD** [sindresorhus/notifier-for-github#134] opened 2017-10-01 15:57 UTC
I recently got an issue that the addon does not show the badges anymore until i click on it.. After that it fetches the count just fine, until i restart the browser. I am using Opera, and installed it via https://addons.opera.com/de/extensions/details/download-chrome-extension-9/?display=en

**Comment by pasindujw** [comment] 2018-06-08 00:36
Same happened with Chrome.

**Comment by notlmn** [comment] 2018-06-29 17:35
Duplicate of #132.

**Closed by notlmn** 2018-06-29 17:35 UTC
